### ISSUE TITLE
Unable to set Smtp Type via UI

### ISSUE THREAD

**Issue by LukasK13** [PrefectHQ/prefect-email#28]
When setting up the EmailServerCredentials block via the UI, the field Smtp Type accepts only JSON type. Therefore the value must be supplied as quoted string, e.g. `"INSECURE"`.
This results however in the following error message when trying to send a message:
```
ValueError: Must be one of ['SSL', 'STARTTLS', 'INSECURE']; got '"INSECURE"'
```

When the input field is left empty, the error message looks as follows:
```
ValueError: Must be one of ['SSL', 'STARTTLS', 'INSECURE']; got ''
```

**Comment by ahuang11** [comment]
Thanks for reporting this. There will be an incoming UI upgrade; in the meantime, a work around is saving the value in quotes and stripping the quotes afterwards:

```
from prefect_email import EmailServerCredentials
email_credentials_block = EmailServerCredentials.load("testing")
email_credentials_block = email_credentials_block.smtp_server.strip('"')
```

Once the UI is updated, you can edit the existing block to drop the quotes and code to drop `strip`:
![image](https://user-images.githubusercontent.com/15331990/189399643-6dbc4044-0a93-43aa-b1f7-675a1b2c1aad.png)

**Comment by LukasK13** [comment]
Thank you for the temporary workaround. Which UI update will include the fix?
For anyone else stumbling upon this, the following workaround works for me. Note that both `smtp_server` and `smtp_type` have to be stripped and reassigned.

```
email_server_credentials = EmailServerCredentials.load("my-mail-block")
email_server_credentials.smtp_server = email_server_credentials.smtp_server.strip('"')
email_server_credentials.smtp_type = email_server_credentials.smtp_type.strip('"')
```

**Comment by ahuang11** [comment]
I couldn't find the issue; but I believe @desertaxle talked to the UI team about this.
