### ISSUE TITLE
username and password mandatory even if EmailServerCredentials is using an INSECURE server

### ISSUE THREAD

**Issue by drfraser** [PrefectHQ/prefect-email#40]
Username and password should be set as Optional as they aren't required if your code is connecting to a server not requiring login information. And what if things are set up such that SSL is used to secure the connection (e.g. server and client certificates used as authentication), but no account info is needed? Then server.login() shouldn't be called (line 146 in credentials.py). Unusual perhaps but technically possible.

**Comment by ahuang11** [comment]
Yes that makes sense; thanks for exploring these edge cases!
